version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  setup_on_container:
    docker:
      - image: cimg/python:3.7.11
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Clone YOLOv5 resources
          command: |
            git clone https://github.com/ultralytics/yolov5
      - run:
          name: Set up MaskDataSet from ROBOFLOW (needs registration)
          command: |
            mkdir MaskDataSet
            cd MaskDataSet
            curl -L "https://public.roboflow.com/ds/9rYgiWaqnY?key=$ROBOFLOW_KEY" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip
            cp ../data.yaml .
            cd ..
      - persist_to_workspace:
          root: .
          paths:
            - "yolov5"
            - "MaskDataSet"

  train_to_evaluate_on_gpu:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-2004-cuda-11.4:202110-01
    steps:
      - checkout
      - run:
          name: Check GPU status
          command: nvidia-smi
      - attach_workspace:
          at: .

workflows:
  mask_detection_training:
    jobs:
      - setup_on_container:
          context:
            - docker
